#ifndef WEBSOCKET_VERSION_H
#define WEBSOCKET_VERSION_H

#define WEBSOCKET_VERSION_MAJOR 0
#define WEBSOCKET_VERSION_MINOR 0
#define WEBSOCKET_VERSION_PATCH 1
#define WEBSOCKET_VERSION "0.0.1"

#endif
