#ifndef WEBSOCKET_CLIENT_VERSION_H
#define WEBSOCKET_CLIENT_VERSION_H

#define WEBSOCKET_CLIENT_VERSION_MAJOR 0
#define WEBSOCKET_CLIENT_VERSION_MINOR 0
#define WEBSOCKET_CLIENT_VERSION_PATCH 1
#define WEBSOCKET_CLIENT_VERSION "0.0.1"

#endif
